[package]
name = "tfhe_sql_query"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "integer", "shortint", "x86_64-unix"] }
sqlparser=  { version = "*" }
serde =  { version = "*" }
csv =  { version = "*" }
