[package]
name = "tfhe_sql_query"
version = "0.1.0"
edition = "2021"

[dependencies]
csv =  { version = "*" }
dyn-stack = { version = "0.9" }
serde =  { version = "*" }
sqlparser=  { version = "*" }
tfhe = { version = "*", features = ["boolean", "integer", "shortint", "x86_64-unix"] }
